routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('fpos.index');
});

Route::resource('procedimentos', 'ProcedimentoController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('unidades_saude', 'UnidadeSaudeController')->parameters(['unidades_saude' => 'unidade_saude']);

Route::resource('fpos', 'FpoController');

app/Fpo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Fpo
 * @package App
 */
class Fpo extends Model
{
    /**
     * @var array
     */
    protected $fillable = ['id', 'unidade_saude_id', 'valor_total', 'nivel_apuracao', 'cmpt_ini'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function procedimentos()
    {
        return $this->belongsToMany(Procedimento::class, 'procedimento_fpos')
            ->using(ProcedimentoFpo::class)
            ->withPivot('quantidade');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function unidade_saude()
    {
        return $this->belongsTo(UnidadeSaude::class);
    }

    /**
     * @param float $value
     */
    public function setValorTotal($value)
    {
        $this->attributes['valor_total'] = $value;
    }
}

app/Http/Controllers/FpoController.php
<?php

namespace App\Http\Controllers;

use App\Fpo;
use App\Procedimento;
use App\UnidadeSaude;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FpoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $fpos = Fpo::all();

        /** @var Fpo $fpo */
        foreach ($fpos as $fpo) {
            $valor_total = 0;
            foreach($fpo->procedimentos as $procedimento) {
                /** @var Pivot $pivot */
                $quantidade = $procedimento->pivot->quantidade;
                $valor = floatval($procedimento->valor_unitario);
                $valor_total += $valor * $quantidade;
            }
            $fpo->setValorTotal($valor_total);
            $fpo->save();
        }

        return view('fpos.index', compact('fpos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response|RedirectResponse
     */
    public function create()
    {
        if (Auth::check()) {
            $unidades = UnidadeSaude::all();
            $procedimentos = Procedimento::all();
            return view('fpos.create', compact('unidades', 'procedimentos'));
        } else {
            return $this->noAuth();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response|RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'unidade_saude_id' => 'required',
            'nivel_apuracao' => 'required',
            'cmpt_ini' => 'required',
        ]);

        $data = $request->all();

        $cmpt_ini = $request->input('cmpt_ini');
        $cmpt_ini = date('Y-m-d', strtotime($cmpt_ini));
        $data['cmpt_ini'] = $cmpt_ini;
        $data['valor_total'] = 0;

        /** @var Fpo $fpo */
        $fpo = Fpo::create($data);

        if (!empty($data['procedimentos'])) {
            $quantidades_procedimentos = $data['procedimentos'];
            $ids_procedimentos = array_keys($quantidades_procedimentos);
            $procedimentos = Procedimento::findMany($ids_procedimentos);
            $valor_total = 0;
            foreach ($procedimentos as $procedimento) {
                $valor_total += $procedimento->valor_unitario * $quantidades_procedimentos[$procedimento->id];
            }

            $fpo->setValorTotal($valor_total);

            foreach ($quantidades_procedimentos as $id_procedimento => $quantidade) {
                $fpo->procedimentos()->attach($id_procedimento, ['quantidade' => $quantidade]);
            }

            $fpo->save();
        }

        return redirect()->route('fpos.index')
            ->with('success','FPO criada com sucesso.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Fpo  $fpo
     * @return \Illuminate\Http\Response|RedirectResponse
     */
    public function show(Fpo $fpo)
    {
        if (Auth::check()) {
            $valor_total = 0;
            foreach($fpo->procedimentos as $procedimento) {
                /** @var Pivot $pivot */
                $quantidade = $procedimento->pivot->quantidade;
                $valor = floatval($procedimento->valor_unitario);
                $valor_total += $valor * $quantidade;
            }
            $fpo->setValorTotal($valor_total);
            $fpo->save();

            return view('fpos.show', compact('fpo'));
        } else {
            return $this->noAuth();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Fpo  $fpo
     * @return \Illuminate\Http\Response
     */
    public function edit(Fpo $fpo)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Fpo  $fpo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Fpo $fpo)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Fpo  $fpo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Fpo $fpo)
    {
        if (Auth::check()) {
            $fpo->delete();

            return redirect()->route('fpos.index')
                ->with('success', 'FPO removida com sucesso');
        } else {
            return $this->noAuth();
        }
    }

    /**
     * @return \Illuminate\Http\RedirectResponse
     */
    private function noAuth()
    {
        return redirect()
            ->route('fpos.index')
            ->with('error', 'É preciso estar logado para realizar esta ação.');
    }

    private function calculateTotalValue() {

    }
}

resources/views/fpos/create.blade.php
@extends('base')

@section('header', 'Cadastrar FPO')

@section('conteudo')
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show">
            <strong>Erro!</strong><br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <form action="{{ route('fpos.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="unidade_saude">Unidade de saúde</label>
            <select id="unidade_saude" name="unidade_saude_id" required class="form-control">
                @foreach($unidades as $unidade)
                    <option value="{{$unidade->id}}">{{$unidade->nome}}</option>
                @endforeach
            </select>
            <div class="form-group">
                <label for="nivel_apuracao">Nível de apuração</label>
                <input required type="number" class="form-control" id="nivel_apuracao" name="nivel_apuracao" placeholder="Nível de apuração da FPO">
            </div>
            <div class="form-group">
                <label for="cmpt_ini">Competência</label>
                <input required type="month" class="form-control" id="cmpt_ini" name="cmpt_ini">
            </div>
            <div class="card">
                <h5 class="card-header">Procedimentos</h5>
                <div class="card-body">
                    <div class="form-group">
                        <input type="text" class="form-control" id="search-procedimentos" placeholder="Pesquisar">
                    </div>
                    <table id="table-procedimentos" class="table table-striped header-fixed" style="table-layout: fixed">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Código do procedimento</th>
                            <th scope="col">Descrição</th>
                            <th scope="col">Valor unitário</th>
                            <th scope="col">Ação</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($procedimentos as $procedimento)
                            <tr>
                                <td>{{$procedimento->id}}</td>
                                <td>{{$procedimento->codigo_procedimento}}</td>
                                <td>{{$procedimento->descricao}}</td>
                                <td>@money($procedimento->valor_unitario)</td>
                                <td>
                                    <div class="row">
                                        <button onclick="openModal(this)" type="button" class="btn btn-primary"
                                                data-toggle="modal"
                                                data-target="#add-procedimento-modal"
                                                data-id="{{$procedimento->id}}"
                                                data-valor="{{$procedimento->valor_unitario}}"
                                                data-codigo="{{$procedimento->codigo_procedimento}}"
                                                data-descricao="{{$procedimento->descricao}}">
                                            <i class="material-icons">add</i>&nbsp;Adicionar
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <br><br>
            <div class="card">
                <h5 class="card-header">FPO</h5>
                <div class="card-body">
                    <div class="form-group">
                        <input type="text" class="form-control" id="search-added-procedimentos" placeholder="Pesquisar">
                    </div>
                    <table id="table-added-procedimentos" class="table table-striped" style="table-layout: fixed">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Procedimento</th>
                            <th scope="col">Quantidade</th>
                            <th scope="col">Valor total</th>
                            <th scope="col">Ação</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
            <div id="procedimentos"></div>
            <br><br>
            <div class="form-group">
                <label for="valor_total_label">Valor total</label>
                <input readonly type="text" class="form-control" id="valor_total_label">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>

    </form>
@endsection

@push('scripts')
    <script src="{{ asset('js/fpo.js') }}"></script>
@endpush

<!-- Modal -->
<div class="modal fade" id="add-procedimento-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Adicionar procedimento</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="add-procedimento-form">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="procedimento">Procedimento</label>
                        <input required type="text" readonly class="form-control" id="procedimento">
                    </div>
                    <div class="form-group">
                        <label for="quantidade">Quantidade</label>
                        <input required type="number" class="form-control" id="quantidade">
                    </div>
                    <div class="form-group">
                        <label for="valor">Valor</label>
                        <input required type="text" readonly class="form-control" id="valor">
                    </div>
                    <input type="hidden" id="valor-modal">
                    <input type="hidden" id="id-procedimento">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" id="close-modal" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary" onclick="addProcedimento()">Adicionar</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/fpos/index.blade.php
@extends('base')

@section('header', 'FPOs')

@section('conteudo')
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-dismissible fade show">
            <p>{{ $message }}</p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @if ($message = Session::get('error'))
        <div class="alert alert-danger alert-dismissible fade show">
            <p>{{ $message }}</p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <table class="table table-striped">
        <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Unidade de saúde</th>
            <th scope="col">Competência</th>
            <th scope="col">Valor total</th>
            <th scope="col">Ação</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($fpos as $fpo)
            <tr>
                <td>{{$fpo->id}}</td>
                <td>{{$fpo->unidade_saude()->value('nome')}}</td>
                <td>{{date('m/Y', strtotime($fpo->cmpt_ini))}}</td>
                <td>@money($fpo->valor_total)</td>
                <td style="width: 300px;">
                    <div class="row">
                        <a class="btn btn-primary" style="height:40px" role="button" href="{{route('fpos.show', $fpo->id)}}">
                            <i class="material-icons">pageview</i>&nbsp;Visualizar</a>&nbsp;
                        <form action="{{ route('fpos.destroy', $fpo->id) }}"
                              onsubmit="return window.confirm('Deseja realmente remover a FPO?')" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger"><i class="material-icons">delete</i>&nbsp;Remover</button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/fpos/show.blade.php
@extends('base')

@section('header', 'FPO')

@section('conteudo')
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show">
            <strong>Erro!</strong><br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="form-group">
        <div class="form-group">
            <h6 class="text-muted">Unidade de saúde</h6>
            <h3 class="my-0" style="font-weight: normal">{{$fpo->unidade_saude->nome}}</h3>
        </div>
        <br>
        <div class="form-group">
            <h6 class="text-muted">Nível de apuração</h6>
            <h3 class="my-0" style="font-weight: normal">{{$fpo->nivel_apuracao}}</h3>
        </div>
        <br>
        <div class="form-group">
            <h6 class="text-muted">Competência</h6>
            <h3 class="my-0" style="font-weight: normal">{{date('m/Y', strtotime($fpo->cmpt_ini))}}</h3>
        </div>
        <br>
        <div class="card">
            <h5 class="card-header">FPO</h5>
            <div class="card-body">
                <table id="table-added-procedimentos" class="table table-striped" style="table-layout: fixed">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Procedimento</th>
                        <th scope="col">Quantidade</th>
                        <th scope="col">Valor total</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($fpo->procedimentos as $procedimento)
                        <tr>
                            <td>{{$procedimento->id}}</td>
                            <td>{{$procedimento->codigo_procedimento}} - {{$procedimento->descricao}}</td>
                            <td>{{$procedimento->pivot->quantidade}}</td>
                            <td>@money($procedimento->valor_unitario * $procedimento->pivot->quantidade)</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <br>
        <div class="form-group">
            <h6 class="text-muted">Valor total</h6>
            <h3 class="my-0" style="font-weight: normal">@money($fpo->valor_total)</h3>
        </div>
    </div>
@endsection