routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('fpos.index');
});

Route::resource('procedimentos', 'ProcedimentoController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('unidades_saude', 'UnidadeSaudeController')->parameters(['unidades_saude' => 'unidade_saude']);

Route::resource('fpos', 'FpoController');

resources/views/unidades_saude/create.blade.php
@extends('base')

@section('header', 'Cadastrar unidade de saúde')

@section('conteudo')
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show">
            <strong>Erro!</strong><br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <form action="{{ route('unidades_saude.store') }}" method="POST">
        @csrf

        <div class="form-group">
            <label for="nome">Nome</label>
            <input required type="text" maxlength="255" class="form-control" id="nome" name="nome" placeholder="Nome da unidade de saúde">
        </div>
        <div class="form-group">
            <label for="codigo_cnes">Código CNES</label>
            <input required type="text" maxlength="255" class="form-control" id="codigo_cnes" name="codigo_cnes" placeholder="Código CNES da unidade de saúde">
        </div>
        <div class="form-group">
            <label for="endereco">Endereço</label>
            <input required type="text" maxlength="255" class="form-control" id="endereco" name="endereco" placeholder="Endereço da unidade de saúde">
        </div>
        <div class="form-group">
            <label for="diretor_clinico">Diretor clínico</label>
            <input required type="text" maxlength="255" class="form-control" id="diretor_clinico" name="diretor_clinico" placeholder="Diretor clínico da unidade de saúde">
        </div>
        <div class="form-group">
            <label for="horario_funcionamento">Horário de funcionamento</label>
            <select id="horario_funcionamento" name="horario_funcionamento" required class="form-control">
                @foreach($horarios_funcionamento as $key => $horario)
                    <option value="{{$key}}">{{$horario}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="natureza_juridica">Natureza jurídica</label>
            <select id="natureza_juridica" name="natureza_juridica" required class="form-control">
                @foreach($naturezas_juridicas as $key => $natureza)
                    <option value="{{$key}}">{{$natureza}}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
@endsection

resources/views/unidades_saude/edit.blade.php
@extends('base')

@section('header', 'Editar unidade de saúde')

@section('conteudo')
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show">
            <strong>Erro!</strong><br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    <form action="{{ route('unidades_saude.update', $unidade_saude->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="nome">Nome</label>
            <input value="{{$unidade_saude->nome}}" required type="text" maxlength="255" class="form-control" id="nome" name="nome" placeholder="Nome da unidade de saúde">
        </div>
        <div class="form-group">
            <label for="codigo_cnes">Código CNES</label>
            <input value="{{$unidade_saude->codigo_cnes}}" required type="text" maxlength="255" class="form-control" id="codigo_cnes" name="codigo_cnes" placeholder="Código CNES da unidade de saúde">
        </div>
        <div class="form-group">
            <label for="endereco">Endereço</label>
            <input value="{{$unidade_saude->endereco}}" required type="text" maxlength="255" class="form-control" id="endereco" name="endereco" placeholder="Endereço da unidade de saúde">
        </div>
        <div class="form-group">
            <label for="diretor_clinico">Diretor clínico</label>
            <input value="{{$unidade_saude->diretor_clinico}}" required type="text" maxlength="255" class="form-control" id="diretor_clinico" name="diretor_clinico" placeholder="Diretor clínico da unidade de saúde">
        </div>
        <div class="form-group">
            <label for="horario_funcionamento">Horário de funcionamento</label>
            <select id="horario_funcionamento" name="horario_funcionamento" required class="form-control">
                @foreach($horarios_funcionamento as $key => $horario)
                    <option value="{{$key}}" @if($key == $unidade_saude->horario_funcionamento) selected @endif>{{$horario}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="natureza_juridica">Natureza jurídica</label>
            <select id="natureza_juridica" name="natureza_juridica" required class="form-control">
                @foreach($naturezas_juridicas as $key => $natureza)
                    <option value="{{$key}}" @if($key == $unidade_saude->natureza_juridica) selected @endif>{{$natureza}}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
@endsection

resources/views/unidades_saude/index.blade.php
@extends('base')

@section('header', 'Unidades de saúde')

@section('conteudo')
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-dismissible fade show">
            <p>{{ $message }}</p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @if ($message = Session::get('error'))
        <div class="alert alert-danger alert-dismissible fade show">
            <p>{{ $message }}</p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <table class="table table-striped" style="table-layout: fixed">
        <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Código CNES</th>
            <th scope="col">Nome</th>
            <th scope="col">Endereço</th>
            <th scope="col">Ação</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($unidades_saude as $unidade_saude)
            <tr>
                <td>{{$unidade_saude->id}}</td>
                <td>{{$unidade_saude->codigo_cnes}}</td>
                <td>{{$unidade_saude->nome}}</td>
                <td>{{$unidade_saude->endereco}}</td>
                <td>
                    <div class="row">
                        <a class="btn btn-primary" style="height:40px" role="button" href="{{route('unidades_saude.edit', $unidade_saude->id)}}">
                            <i class="material-icons">edit</i>&nbsp;Editar</a>&nbsp;
                        <form action="{{ route('unidades_saude.destroy', $unidade_saude->id) }}"
                              onsubmit="return window.confirm('Deseja realmente remover a unidade de saúde?')" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger"><i class="material-icons">delete</i>&nbsp;Remover</button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection