routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('fpos.index');
});

Route::resource('procedimentos', 'ProcedimentoController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('unidades_saude', 'UnidadeSaudeController')->parameters(['unidades_saude' => 'unidade_saude']);

Route::resource('fpos', 'FpoController');

app/Procedimento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Procedimento
 * @package App
 */
class Procedimento extends Model
{
    /**
     * @var array
     */
    protected $fillable = ['id', 'codigo_procedimento', 'descricao', 'valor_unitario'];
}

app/Http/Controllers/ProcedimentoController.php
<?php

namespace App\Http\Controllers;

use App\Procedimento;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/**
 * Class ProcedimentoController
 * @package App\Http\Controllers
 */
class ProcedimentoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $procedimentos = Procedimento::all();

        return view('procedimentos.index', compact('procedimentos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response|RedirectResponse
     */
    public function create()
    {
        if (Auth::check()) {
            return view('procedimentos.create');
        } else {
            return $this->noAuth();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'codigo_procedimento' => 'required',
            'descricao' => 'required',
            'valor_unitario' => 'required',
        ]);

        Procedimento::create($request->all());

        return redirect()->route('procedimentos.index')
            ->with('success','Procedimento criado com sucesso.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Procedimento  $procedimento
     * @return \Illuminate\Http\Response
     */
    public function show(Procedimento $procedimento)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Procedimento  $procedimento
     * @return \Illuminate\Http\Response|RedirectResponse
     */
    public function edit(Procedimento $procedimento)
    {
        if (Auth::check()) {
            return view('procedimentos.edit', compact('procedimento'));
        } else {
            return $this->noAuth();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Procedimento  $procedimento
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Procedimento $procedimento)
    {
        $request->validate([
            'codigo_procedimento' => 'required',
            'descricao' => 'required',
            'valor_unitario' => 'required',
        ]);

        $procedimento->update($request->all());

        return redirect()->route('procedimentos.index')
            ->with('success','Procedimento salvo com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Procedimento  $procedimento
     * @return \Illuminate\Http\Response|RedirectResponse
     */
    public function destroy(Procedimento $procedimento)
    {
        if (Auth::check()) {
            $procedimento->delete();

            return redirect()->route('procedimentos.index')
                ->with('success', 'Procedimento removido com sucesso');
        } else {
            return $this->noAuth();
        }
    }

    /**
     * @return \Illuminate\Http\RedirectResponse
     */
    private function noAuth()
    {
        return redirect()
            ->route('procedimentos.index')
            ->with('error', 'É preciso estar logado para realizar esta ação.');
    }
}

resources/views/procedimentos/create.blade.php
@extends('base')

@section('header', 'Cadastrar procedimento')

@section('conteudo')
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show">
            <strong>Erro!</strong><br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <form action="{{ route('procedimentos.store') }}" method="POST">
        @csrf

        <div class="form-group">
            <label for="codigo_procedimento">Código do procedimento</label>
            <input required type="text" maxlength="10" class="form-control" id="codigo_procedimento" name="codigo_procedimento" placeholder="Código do procedimento">
        </div>
        <div class="form-group">
            <label for="descricao">Descrição</label>
            <input required type="text" maxlength="255" class="form-control" id="descricao" name="descricao" placeholder="Descrição do procedimento">
        </div>
        <div class="form-group">
            <label for="valor_unitario">Valor unitário</label>
            <input required type="number" step="any" class="form-control" id="valor_unitario" name="valor_unitario" placeholder="Valor unitário do procedimento">
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>

    </form>
@endsection

resources/views/procedimentos/edit.blade.php
@extends('base')

@section('header', 'Editar procedimento')

@section('conteudo')
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show">
            <strong>Erro!</strong><br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <form action="{{ route('procedimentos.update', $procedimento->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="codigo_procedimento">Código do procedimento</label>
            <input value="{{$procedimento->codigo_procedimento}}" maxlength="10" required type="text" class="form-control" id="codigo_procedimento" name="codigo_procedimento" placeholder="Código do procedimento">
        </div>
        <div class="form-group">
            <label for="descricao">Descrição</label>
            <input value="{{$procedimento->descricao}}" maxlength="255" required type="text" class="form-control" id="descricao" name="descricao" placeholder="Descrição do procedimento">
        </div>
        <div class="form-group">
            <label for="valor_unitario">Valor unitário</label>
            <input value="{{$procedimento->valor_unitario}}" required type="number" step="any" class="form-control" id="valor_unitario" name="valor_unitario" placeholder="Valor unitário do procedimento">
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>

    </form>
@endsection

resources/views/procedimentos/index.blade.php
@extends('base')

@section('header', 'Procedimentos')

@section('conteudo')
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-dismissible fade show">
            <p>{{ $message }}</p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @if ($message = Session::get('error'))
        <div class="alert alert-danger alert-dismissible fade show">
            <p>{{ $message }}</p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="form-group">
        <input type="text" class="form-control" id="search-procedimentos" placeholder="Pesquisar">
    </div>
    <table class="table table-striped" id="table-procedimentos" style="table-layout: fixed">
        <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Código do procedimento</th>
            <th scope="col">Descrição</th>
            <th scope="col">Valor unitário</th>
            <th scope="col">Ação</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($procedimentos as $procedimento)
            <tr>
                <td>{{$procedimento->id}}</td>
                <td>{{$procedimento->codigo_procedimento}}</td>
                <td>{{$procedimento->descricao}}</td>
                <td>@money($procedimento->valor_unitario)</td>
                <td>
                    <div class="row">
                        <a class="btn btn-primary" style="height:40px" role="button" href="{{route('procedimentos.edit', $procedimento->id)}}">
                            <i class="material-icons">edit</i>&nbsp;Editar</a>&nbsp;
                        <form action="{{ route('procedimentos.destroy', $procedimento->id) }}"
                              onsubmit="return window.confirm('Deseja realmente remover o procedimento?')" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger"><i class="material-icons">delete</i>&nbsp;Remover</button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection
@push('scripts')
    <script src="{{ asset('js/fpo.js') }}"></script>
@endpush